version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend  # Reference to your Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - ./energy_estimation.db:/app/energy_estimation.db
    env_file: .env
    depends_on:
      - frontend  # Ensure backend starts after frontend if needed

  frontend:
    build:
      context: ./front-end  # Ensure this points to the correct directory
      dockerfile: Dockerfile.frontend  # Reference to your Dockerfile.frontend
    ports:
      - "3000:3000"