version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"  # React app will still be available on 3000
    depends_on:
      - backend  # Ensure backend is up before frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:5000/"]  # Check if backend is ready
      interval: 10s  # Check every 10 seconds
      retries: 5     # Retry 5 times before considering it unhealthy
      start_period: 30s  # Give the backend 30 seconds to start before checking health
    environment:
      - REACT_APP_API_URL=http://backend:5000  # Set the backend URL for frontend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"  # Backend will be available on 5000
    volumes:
      - ./energy_estimation.db:/app/energy_estimation.db
      - ./frontend/build:/app/static/react_build  # Mount the React build folder to backend
    env_file: .env
    depends_on:
      - frontend  # Ensure frontend build happens before backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]  # Check if backend is responding
      interval: 10s  # Check every 10 seconds
      retries: 5     # Retry 5 times before considering it unhealthy
      start_period: 30s  # Give the backend 30 seconds to start before checking health