version: '3.8'
services:
  backend:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./energy_estimation.db:/app/energy_estimation.db
    env_file: .env

  frontend:
    build:
      context: ./front-end
    ports:
      - "3000:3000"