version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    # Remove the 'depends_on' attribute for frontend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - ./energy_estimation.db:/app/energy_estimation.db
      - ./frontend/build:/app/static/react_build  # Mount React build folder to backend
    env_file: .env
    # Remove the 'depends_on' attribute for backend