version: '3.8'
services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile.frontend
    command: npm run build  # Build the React app
    volumes:
      - ./front-end/build:/app/build  # This mounts the build folder to the backend

  backend:
    build:
      context: .  # Path to the backend Dockerfile
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - ./energy_estimation.db:/app/energy_estimation.db
      - ./front-end/build:/app/static/react_build  # Mount the React build to the backend
    env_file: .env
    depends_on:
      - frontend  # Ensure frontend build happens before backend