# Dockerfile.backend

FROM python:3.12-slim

WORKDIR /app

# Install backend dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy backend code
COPY . .

# The build folder is already mounted as a volume from docker-compose
# No need to copy it manually anymore

# Command to run the Flask app
CMD ["python", "app.py"]