version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - ./energy_estimation.db:/app/energy_estimation.db
    env_file: .env
    depends_on:
      - frontend

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    command: npm run build && npm install -g serve && serve -s build -l 3000