version: '3.8'

services:
  frontend:
    build:
      context: ./front-end  # Path to the frontend folder
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    command: npm run build  # Build the React app

  backend:
    build:
      context: .  # This is the directory where the backend Dockerfile exists
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - ./energy_estimation.db:/app/energy_estimation.db
    env_file: .env
    depends_on:
      - frontend  # Ensure frontend build finishes before backend builds