version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "5000:5000"
    # volumes:
    #   - ./energy_estimation.db:/app/energy_estimation.db
    env_file: .env